version: "3.8"

services:
  reverse_proxy:
    image: nginx
    ports:
    - 3214:80
    volumes:
      # Two dots are the equivalent of './'
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "nginx_cache:/data/nginx/cache"

volumes:
  nginx_cache:
